# Use a imagem base do Python
FROM python:3.9-slim

# Instala dependências do sistema
RUN apt-get update && apt-get install -y netcat-openbsd iputils-ping && rm -rf /var/lib/apt/lists/*

# Define o diretório de trabalho
WORKDIR /app

# Copia o requirements.txt e instala as dependências
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# Copia o conteúdo do projeto para o diretório de trabalho
COPY . .

# Executa o script Python
CMD ["python", "seu_script.py"]
