version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: chuck
      MYSQL_DATABASE: db_taco
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  app:
    build: .
    command: ./wait-for-it.sh db:3306 -- flask run --host=0.0.0.0 --port=5000
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db

  script:
    build:
      context: .
      dockerfile: Dockerfile.script
    command: ./wait-for-it.sh db:3306 -- python script_taco.py
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  db_data:

  